---
- name: Ensure munin.conf
  template: src={{ item }} dest={{ munin_master_file_conf }} backup=no owner=root group=root mode=0644
  with_first_found:
    - "munin.conf.{{ ansible_os_family }}.j2"
    - "munin.conf.default.j2"
  when: munin_role_master == true

#TODO# Ensure directories are present and owner/group/perms.

- name: Declare node in master
  template: src="munin-host.j2" dest="{{ munin_master_includedir }}/{{ ansible_fqdn }}_{{ munin_node_port }}" backup=no owner=root group=root mode=0644
  delegate_to: "{{ munin_master_ip }}"
  when: munin_role_node == true and munin_master_ip != false

- name: Declare node locally
  template: src="munin-host.j2" dest="{{ munin_master_includedir }}/{{ ansible_fqdn }}_{{ munin_node_port }}" backup=no owner=root group=root mode=0644
  when: munin_role_node == true and munin_master_ip == false

- name: Ensure munin-node.conf
  template: src={{ item }} dest={{ munin_node_file_conf }} backup=no owner=root group=root mode=0644
  with_first_found:
    - "munin-node.conf.{{ ansible_os_family }}.j2"
    - "munin-node.conf.default.j2"
  when: munin_role_node == true

- name: Ensure custom plugins directory
  file:
  args:
    state: directory
    path: "{{ munin_node_dir_plugins_custom }}"
  when: munin_role_node == true

